server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
    context-path: /
    #上下文
spring:
  mvc:
    format:
      date: yyyy-MM-dd
  thymeleaf:
    cache: false
  datasource:
    driver-class-name:org.postgresql.Driver
    url:jdbc:postgresql://47.105.27.15:5432/springboot
    data-username:postgres
    data-password:postgres
